main:
  push:
    - name: push to github
      stages:
        - name: sync to github #向github推代码
          imports: https://cnb.cool/kic-for-own/github-secr/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/kenichiLyon/sealdice-mcsm
            auth_type: https
            username: "$GIT_USERNAME" # 如果使用 HTTPS
            password: "$GIT_PASSWORD" # 如果使用 HTTPS
            force: true # 强制推