main:
  push:
    - name: push to github
      stages:
        - name: sync to github #向github推代码
          imports: https://cnb.cool/kic-for-own/github-secr/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/kenichiLyon/sealdice-mcsm
            auth_type: https
            username: "$GIT_USERNAME" # 如果使用 HTTPS
            password: "$GIT_PASSWORD" # 如果使用 HTTPS
            force: true # 强制推
    - name: auto build
    - stages: 
      - name: Auto Create Release
        imports: https://cnb.cool/kic-for-own/github-secr/-/blob/main/env.yml
        script: |
          # 调用CNB API创建Release（需替换为你的仓库信息）
          RELEASE=$(curl --location "https://cnb.cool/kic-for-own/kenichiLyon/sealdice-mcsm/releases" \
                --header "Authorization: Bearer $CNB_BUILD_TOKEN" \
                --header "Content-Type: application/json" \
                --header "Accept: application/vnd.cnb.api+json" \
                --data "{
                  \"name\": \"自动发布-${CNB_BRANCH}\",
                  \"body\": \"自动生成的Release，包含最新代码构建制品\",
                  \"is_draft\": false,
                  \"is_prerelease\": false,
                  \"make_latest\": true,  # 可选：设为true则自动设为最新版本
                  \"tag_name\": \"${CNB_BRANCH}\",  # 与分支名一致（如main）
                  \"target_commitish\": \"main\"
                }")
          echo "$RELEASE" | jq -r '.id' > release_id.txt  # 保存Release ID到文件
          echo "创建Release成功，ID：$(cat release_id.txt)"

      - name: server build
        docker:
            image: golang:latest
            args: ["--platform=windows/amd64"]
            env:
              - CGO_ENABLED=0
              - GOOS=windows
              - GOARCH=amd64
            script: |
              go mod download
              go build -o /server/sealdice-mcsm-server_windows_amd64.exe
              go build -o /server/sealdice-mcsm-server_linux_amd64
              go build -o /server/sealdice-mcsm-server_darwin_amd64
      - name: plugin build
        docker:
          image: node:latest
          script: |
            npm install
            npm run build

  "crontab: 0 1 * * *": # 每天1点执行
    - name: sync from github
      stages:
        - name: sync from github
          image: tencentcom/git-sync
          settings:
            imports: https://cnb.cool/kic-for-own/github-secr/-/blob/main/env.yml
            target_url: https://github.com/kenichiLyon/sealdice-mcsm.git
            auth_type: https
            username: $GIT_USERNAME
            password: $GIT_ACCESS_TOKEN
            sync_mode: pull